### ISSUE TITLE
Can it work with RavenDB Embedded

### ISSUE THREAD

**Issue by djordjedjukic** [serilog/serilog-sinks-ravendb#13]
Can this plugin work with RavenDB Embedded version?
Thanks

**Comment by viceroypenguin** [comment]
Yes, there is no difference between the Embedded vs the Regular version of RavenDB. 

However, this library will not instantiate the embedded version for you. You would need to instantiate the RavenDB server first and then provide the connection string to this sink.

**Comment by djordjedjukic** [comment]
Great.
One more question, is it possible to send logs in batches with delay or something similar?
Or I need to implement that by myself?

**Comment by viceroypenguin** [comment]
By default, the sink batches 50 events over 2 seconds before sending to RavenDB. There are two parameters (`batchPostingLimit` for how many events, and `period` for maximum wait) to control this. You can provide them as desired.

**Comment by djordjedjukic** [comment]
Oh, I didn't look at doc carefully. Thank you

**Comment by viceroypenguin** [comment]
No worries! Glad I could help!

**Comment by djordjedjukic** [comment]
Hey, I have one more question :)
I would like to use the same database for application and for logging. Do you think, that could cause some problems?

**Comment by viceroypenguin** [comment]
There are no problems with that, as long as you don't use the same collection for both events and application data. This sink will store log entries under the `LogEvents` collection, so as long as you didn't use that collection, you would be fine.

However, I would recommend two separate databases on the same server (which you can do with embedded as well), just for ease of query and separation of concerns.

**Comment by djordjedjukic** [comment]
OK, that's it for now. 
Thank you for really fast responses :)
