### ISSUE TITLE
How do Set Expiration For Document

### ISSUE THREAD

**Issue by MohMehrnia** [serilog/serilog-sinks-ravendb#14]
How do Set Expiration For Document?

**Comment by viceroypenguin** [comment]
There are three parameters to the `.RavenDB()` extension method. They are described as follows:

### Automatic Log Record Expiration

If you install the RavenDB expiration bundle on the database where log records are stored, you can configure the
sink to automatically delete log records. There are two ways to do this:
* Simple version: passing `errorExpiration` (for fatal and error messages) and `expiration` (for all other messages). If you pass one, you should pass both. `Timeout.InfiniteTimeSpan` indicates that messages of the appropriate type will never be deleted by the expiration bundle.
* Featured version: passing `logExpirationCallback`, a which will receive a Serilog `LogEvent` and return a `TimeSpan`. `Timeout.InfiniteTimeSpan` indicates that the message will never be deleted by the expiration bundle.

**Comment by MohMehrnia** [comment]
I write this code 
```
Log.Logger  = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .MinimumLevel.Debug()
                .WriteTo.Console()
                .WriteTo.RavenDB(CreateRavenDocStore(env))
                .CreateLogger();
```
i can not found anywhere for inject errorExpiration

**Comment by MohMehrnia** [comment]
thanks

**Comment by viceroypenguin** [comment]
Sure thing! Glad you got it squared away!
