### ISSUE TITLE
Move this package to @ravendb

### ISSUE THREAD

**Issue by viceroypenguin** [serilog/serilog-sinks-ravendb#15]
See [serilog/serilog#1627](https://github.com/serilog/serilog/issues/1627)

* [x]  Transfer repository
* [x]  Transfer NuGet Package
* [ ]  Move CI

**Comment by viceroypenguin** [comment]
@nblumhardt  - I do not have the repo permissions to handle any of the three, but I can help as necessary.

**Comment by nblumhardt** [comment]
Ping @augustoprioete - I can kick this one off if you think @serilog-contrib is an appropriate home? Or otherwise, let me know, I'll shuffle it to `serilog-archive` :-)

**Comment by viceroypenguin** [comment]
You know what, I think `serilog-archive` would be just fine. The current version works well with latest versions of ravendb and serilog, and I'm about to switch off the project where I was using ravendb, so I won't be dogfooding this anymore. Nuget downloads are somewhat low, so there likely aren't very many people using it either. If an issue ever comes up with a breaking change, someone can fork and reopen as needed.

**Comment by nblumhardt** [comment]
👍 thanks @viceroypenguin

**Comment by nblumhardt** [comment]
Hi all! @DejanMilicic from RavenDB is taking over this project, which will move to the @ravendb org.
